"""add sort_order to property_images

Revision ID: 4403ea490df8
Revises: 
Create Date: 2026-01-13 22:18:13.434639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4403ea490df8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_property_images_sort_order'), ['sort_order'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_images_sort_order'))
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###
