"""Add valuta column

Revision ID: ad706c92a0c9
Revises: 4403ea490df8
Create Date: 2026-01-16 18:33:57.327719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad706c92a0c9'
down_revision = '4403ea490df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valuta', sa.String(length=3), nullable=False))
        batch_op.create_index(batch_op.f('ix_property_valuta'), ['valuta'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_valuta'))
        batch_op.drop_column('valuta')

    # ### end Alembic commands ###
